apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 231298815176.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:f8a0a8f67fe2b4df5914ab170e0fb232ad9675c5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earphones-service
  labels:
    app: earphones
spec:
  type: ClusterIP
  selector:
    app: earphones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
